version: '3.8'

services:
  python_service:
    build:
      context: ./python_service
    ports:
      - "8000:8000"

  csharp_service:
    build:
      context: ./csharp_service
    ports:
      - "8081:8080"  # Change external port from 8080 to 8081
