pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/VaibhavBhawsar/LocalMicroserviceSystem.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose build'
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose up -d'
                sh 'curl -s http://localhost:8000'
                sh 'curl -s http://localhost:8080'
            }
        }
    }
}
